# Generated by Django 5.0.7 on 2024-07-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_delete_teacher_remove_student_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.IntegerField()),
                ('Desc', models.TextField()),
            ],
        ),
    ]
